<a href="https://colab.research.google.com/github/deathbuycactus/deathbuycactus.github.io/blob/main/week1_assignment1_pandas_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Assignment - Pandas exercises

## Data

This assignment uses 2019 flight statistics from the United States Department of Transportationâ€™s Bureau of Transportation Statistics (available [here](https://www.transtats.bts.gov/DL_SelectFields.asp?gnoyr_VQ=FMF&QO_fu146_anzr=Nv4%20Pn44vr45) and in this repository as `data/T100_MARKET_ALL_CARRIER.zip`). Each row contains information about a specific route for a given carrier in a given month (e.g., JFK &rarr; LAX on Delta Airlines in January). There are 321,409 rows and 41 columns. Note that you don't need to unzip the file to read it in with `pd.read_csv()`.

## Exercises

##### 1. Read in the data and convert the column names to lowercase to make them easier to work with.

In [3]:
import pandas as pd
import numpy as np
#flights = pd.read_csv("./data/T100_MARKET_ALL_CARRIER.zip")
flights = pd.read_csv("./T100_MARKET_ALL_CARRIER.zip")
flights.columns = flights.columns.str.lower()
flights

,passengers,freight,mail,distance,unique_carrier,airline_id,unique_carrier_name,unique_carrier_entity,region,carrier,...,dest_state_nm,dest_country,dest_country_name,dest_wac,year,quarter,month,distance_group,class,data_source
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,Texas,US,United States,74,2019,1,3,17,G,IF
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,New York,US,United States,22,2019,1,3,14,G,IF
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,Illinois,US,United States,41,2019,1,3,15,G,IF
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,17,G,IF
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,NaN,AE,United Arab Emirates,678,2019,1,3,14,G,IF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,7,3,F,DU
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,2,6,3,F,DU
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Washington,US,United States,93,2019,3,8,3,F,DU
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,Georgia,US,United States,34,2019,1,3,1,F,DU
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,Alaska,US,United States,1,2019,3,7,3,F,DU

##### 2. What columns are in the data?

In [4]:
flights_columns = flights.columns
flights_columns

Index(['passengers', 'freight', 'mail', 'distance', 'unique_carrier',
       'airline_id', 'unique_carrier_name', 'unique_carrier_entity', 'region',
       'carrier', 'carrier_name', 'carrier_group', 'carrier_group_new',
       'origin_airport_id', 'origin_airport_seq_id', 'origin_city_market_id',
       'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_fips',
       'origin_state_nm', 'origin_country', 'origin_country_name',
       'origin_wac', 'dest_airport_id', 'dest_airport_seq_id',
       'dest_city_market_id', 'dest', 'dest_city_name', 'dest_state_abr',
       'dest_state_fips', 'dest_state_nm', 'dest_country', 'dest_country_name',
       'dest_wac', 'year', 'quarter', 'month', 'distance_group', 'class',
       'data_source'],
      dtype='object')

##### 3. How many distinct carrier names are in the dataset?

In [5]:
flights_carriers = flights['carrier_name'].nunique()
flights_carriers

319

##### 4. Calculate the totals of the `freight`, `mail`, and `passengers` columns for flights from the United Kingdom to the United States.

In [6]:
flights_US = flights.drop(flights[flights['dest_country_name'] != "United States"].index)
UK_US = flights_US.drop(flights_US[flights_US['origin_country_name'] != "United Kingdom"].index)
freight = UK_US.freight.sum()
mail = UK_US.mail.sum()
passengers = UK_US.passengers.sum()
print(freight)
print(mail)
print(passengers)
#UK_US.head(50)

903296879.0
29838395.0
10685608.0

##### 5. Find the top 5 carriers for median route distance (i.e., for all origin-destination pairs that each carrier has, find the median distance after removing duplicates).

<span style='color: red'>Marcus</span>

You're doing a great job!  Keep it up.  See my comments in the cell below.  This question is simply asking you to find the median distance of all unique routes.  You can use drop duplicates to get rid of dupes, and then use groupby and media to do the rest.  I'll show you how to drop duplicates.  You can use the "median" function to get the median of each group after that.  Remember that "nlargest" will allow you to get rows by the largest values in a column

In [7]:
# I honestly don't understand how to approach this question from what its asking
unique_trips = flights.drop_duplicates(['unique_carrier_name','origin','dest','distance'])

# Note that median returns a series
unique_trips.groupby("unique_carrier_name").distance.median()

# Since we want to perform new operations, we want a new dataframe.  That's what the reset_index does
unique_trips.groupby("unique_carrier_name").distance.median().reset_index(name="median_distance")\
    .nlargest(5,'median_distance')

                                   unique_carrier_name  median_distance
248                            Singapore Airlines Ltd.           8068.0
84                         Cathay Pacific Airways Ltd.           8020.0
230                                Qantas Airways Ltd.           7886.0
191                             Longtail Aviation Ltd.           7855.5
204  National Aviation Company of India Limited d/b...           7798.0

##### 6. Find the total cargo transported (mail + freight) and mean distance traveled for the 10 carriers that transported the most cargo.

In [8]:
mail_by_carrier = flights.groupby('carrier_name')['mail'].sum().reset_index()
freight_by_carrier = flights.groupby('carrier_name')['freight'].sum().reset_index()
cargo_by_carrier = pd.merge(mail_by_carrier, freight_by_carrier, on='carrier_name', how='outer')
cargo_by_carrier['cargo'] = cargo_by_carrier['mail'] + cargo_by_carrier['freight']
cargo_by_carrier = cargo_by_carrier.sort_values(by='cargo', ascending = False)
cargo_by_carrier.head(10)

                    carrier_name         mail       freight         cargo
132  Federal Express Corporation    1043019.0  1.270862e+10  1.270966e+10
298        United Parcel Service  276229553.0  8.897637e+09  9.173867e+09
56                Atlas Air Inc.          0.0  3.356847e+09  3.356847e+09
297        United Air Lines Inc.  271718792.0  1.306173e+09  1.577892e+09
50        American Airlines Inc.  220489726.0  1.132585e+09  1.353074e+09
175              Kalitta Air LLC  101850069.0  1.170330e+09  1.272180e+09
225      Polar Air Cargo Airways          0.0  1.199386e+09  1.199386e+09
109         Delta Air Lines Inc.  244050756.0  8.854732e+08  1.129524e+09
89           China Airlines Ltd.          0.0  8.370799e+08  8.370799e+08
85   Cathay Pacific Airways Ltd.          0.0  7.741777e+08  7.741777e+08

##### 7. Which 10 carriers flew the most passengers out of the United States to another country?

In [9]:
us_out = flights.drop(flights[flights['origin_country_name'] != "United States"].index)
passenger_by_carrier = us_out.groupby('carrier_name')['passengers'].sum().reset_index()
passenger_by_carrier = passenger_by_carrier.sort_values(by='passengers', ascending = False)
passenger_by_carrier.head(10)

               carrier_name   passengers
259  Southwest Airlines Co.  160592962.0
109    Delta Air Lines Inc.  149461412.0
50   American Airlines Inc.  140935145.0
296   United Air Lines Inc.  102013933.0
253   SkyWest Airlines Inc.   41675594.0
169         JetBlue Airways   38284436.0
42     Alaska Airlines Inc.   34610251.0
261        Spirit Air Lines   32266068.0
139  Frontier Airlines Inc.   22285466.0
235        Republic Airline   18356886.0

##### 8. For each of the carriers found in *#7*, find the most popular destination country outside of the United States.

In [10]:
carriers = ['Southwest Airlines Co.','Delta Air Lines Inc.','American Airlines Inc.','United Air Lines Inc.','SkyWest Airlines Inc.	','JetBlue Airways','Alaska Airlines Inc.','Spirit Air Lines','Frontier Airlines Inc.	','Republic Airline']
not_us = flights[flights['carrier_name'].isin(carriers)]
not_us = not_us[not_us['dest_country_name'] != 'United States']
# pop_dest["carrier_name"].unique() **Frontier air and Skywest Airliens don't do flights out of the US**
carrier_destination_counts = not_us.groupby(['carrier_name', 'dest_country_name']).size().reset_index(name='count')
top_dests = carrier_destination_counts.groupby('carrier_name')['dest_country_name'].first().reset_index(name='top destination')
top_dests.head(10)

             carrier_name      top destination
0    Alaska Airlines Inc.               Belize
1  American Airlines Inc.  Antigua and Barbuda
2    Delta Air Lines Inc.  Antigua and Barbuda
3         JetBlue Airways  Antigua and Barbuda
4        Republic Airline               Canada
5  Southwest Airlines Co.                Aruba
6        Spirit Air Lines                Aruba
7   United Air Lines Inc.  Antigua and Barbuda

##### 9. For each of the carriers found in *#7*, find the total number of passengers flown on international flights to/from the destinations in *#8* or the United States. Note that this dataset only has data for flights with an origin and/or destination of the United States.

In [11]:
destinations = ['Belize','Antigua and Barbuda','Canada','Aruba', 'United States']
top_carriers = flights[flights['carrier_name'].isin(carriers)]
passenger_counts = top_carriers.groupby(['carrier_name', 'dest_country_name'])['passengers'].sum().reset_index(name='passenger count')
most_popular_carriers = passenger_counts.groupby('carrier_name')['dest_country_name'].first().reset_index(name='Most Popular Destination')
total_passengers = most_popular_carriers.merge(passenger_counts, on=['carrier_name'], how='left')
total_passengers = total_passengers.groupby('carrier_name')['passenger count'].sum().reset_index(name='total passengers')
total_passengers = total_passengers.sort_values(by='total passengers', ascending = False)
total_passengers.head(10)

             carrier_name  total passengers
5  Southwest Airlines Co.       162708484.0
2    Delta Air Lines Inc.       162473055.0
1  American Airlines Inc.       155819193.0
7   United Air Lines Inc.       116328887.0
3         JetBlue Airways        42831297.0
0    Alaska Airlines Inc.        35529786.0
6        Spirit Air Lines        33868007.0
4        Republic Airline        18844915.0

##### 10. Between which two cities were the most passengers flown? Make sure to account for both directions.

<span style="color: red">Marcus</span>
This is a great idea, but doesn't actually answer the question.  "Between" requires we check both origin and dest.  The trick here is to figure out how to do this while ignoring order. One way to do this is by creating a new column with the names of the origin / dest pair sorted alphabetically. See below.

In [12]:
def sort_pair(a,b):
    l = [a,b]
    l.sort()
    return("-".join(l))

# Note that the "axis=1" is important, because it applies the function on a row by row basis
# However, this is super slow; it would probably make more sense to calculate sums on
# unique origin-dest pairs first, and then sort to get route names and sum

flights['route'] = flights.apply(lambda x: sort_pair(x.origin_city_name,x.dest_city_name),axis=1)
flights

# I'll let you figure it out from here :-)

,passengers,freight,mail,distance,unique_carrier,airline_id,unique_carrier_name,unique_carrier_entity,region,carrier,...,dest_country,dest_country_name,dest_wac,year,quarter,month,distance_group,class,data_source,route
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,74,2019,1,3,17,G,IF,"Dubai, United Arab Emirates-Houston, TX"
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,22,2019,1,3,14,G,IF,"Dubai, United Arab Emirates-New York, NY"
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,41,2019,1,3,15,G,IF,"Chicago, IL-Dubai, United Arab Emirates"
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,AE,United Arab Emirates,678,2019,1,3,17,G,IF,"Dubai, United Arab Emirates-Houston, TX"
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,AE,United Arab Emirates,678,2019,1,3,14,G,IF,"Dubai, United Arab Emirates-New York, NY"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,93,2019,3,7,3,F,DU,"Anchorage, AK-Seattle, WA"
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,2,6,3,F,DU,"Anchorage, AK-Seattle, WA"
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,93,2019,3,8,3,F,DU,"Anchorage, AK-Seattle, WA"
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,34,2019,1,3,1,F,DU,"Atlanta, GA-Orlando, FL"
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,3,7,3,F,DU,"Anchorage, AK-Seattle, WA"

In [13]:
top_cities = passenger_counts.groupby('dest_country_name')['passenger count'].sum().nlargest(2).index.tolist()
total_passengers_between_cities = 0


# Whenever possible, avoid for loops!
for destination in top_cities:
    total_passengers_between_cities += passenger_counts[passenger_counts['dest_country_name'] == destination]['passenger count'].sum()
print(f"Between {top_cities[0]} and {top_cities[1]} a total of {total_passengers_between_cities} passengers were flown.")

Between United States and Mexico a total of 685552389.0 passengers were flown.

##### 11. Find the top 3 carriers for the pair of cities found in *#10* and calculate the percentage of passengers each accounted for.

##### 12. Find the percentage of international travel per country using total passengers on class F flights.

In [24]:
flights_region = flights.drop(flights[flights['region'] == "F"].index)
flights_region

,passengers,freight,mail,distance,unique_carrier,airline_id,unique_carrier_name,unique_carrier_entity,region,carrier,...,dest_country,dest_country_name,dest_wac,year,quarter,month,distance_group,class,data_source,route
0,0.0,53185.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,74,2019,1,3,17,G,IF,"Dubai, United Arab Emirates-Houston, TX"
1,0.0,9002.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,22,2019,1,3,14,G,IF,"Dubai, United Arab Emirates-New York, NY"
2,0.0,2220750.0,0.0,7247.0,EK,20392,Emirates,9678A,I,EK,...,US,United States,41,2019,1,3,15,G,IF,"Chicago, IL-Dubai, United Arab Emirates"
3,0.0,1201490.0,0.0,8165.0,EK,20392,Emirates,9678A,I,EK,...,AE,United Arab Emirates,678,2019,1,3,17,G,IF,"Dubai, United Arab Emirates-Houston, TX"
4,0.0,248642.0,0.0,6849.0,EK,20392,Emirates,9678A,I,EK,...,AE,United Arab Emirates,678,2019,1,3,14,G,IF,"Dubai, United Arab Emirates-New York, NY"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321404,96984.0,505308.0,15979.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,93,2019,3,7,3,F,DU,"Anchorage, AK-Seattle, WA"
321405,97011.0,473666.0,55963.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,2,6,3,F,DU,"Anchorage, AK-Seattle, WA"
321406,97098.0,592775.0,18834.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,93,2019,3,8,3,F,DU,"Anchorage, AK-Seattle, WA"
321407,97329.0,210292.0,5431.0,404.0,DL,19790,Delta Air Lines Inc.,01260,D,DL,...,US,United States,34,2019,1,3,1,F,DU,"Atlanta, GA-Orlando, FL"
321408,97644.0,390399.0,44506.0,1448.0,AS,19930,Alaska Airlines Inc.,06031,D,AS,...,US,United States,1,2019,3,7,3,F,DU,"Anchorage, AK-Seattle, WA"

##### 13. Using a crosstab, find the percentage of total passengers on class F international flights between US cities and the countries found in *#12* that used the carriers found in *#11*.

##### 14. Create a pivot table showing the total passengers transported between cities in the United States and other countries by the carriers identified in *#7*. Select the top 10 US cities and top 10 international countries from the result.

##### 15: For the top 15 international countries, find the percentage of class F passengers traveling to/from the top 10 US cities for international travel (e.g. if only cities A, B, and C flew into Aruba, the sum of the Aruba row/column would be 1). Plot the result as a heatmap.